baseURL = "https://whiteppure.github.io/myspace/"
languageCode = "en"
defaultContentLanguage = "en"
title = "whitepure's_blog"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 0
paginate = 10                      # shows the number of articles  # 首页显示文章数量
enableEmoji = false
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "whitepure"

[blackfriday]
  smartypants = false

# config your menu  # 配置菜单
[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = ""                                       # site's subTitle  # 网站二级标题
  footerSlogan = "whitepure@2021"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["whitepure博客","whiteppure","whitepure"]                                  # site's keywords  # 网站关键字
  description = "whitepure's blog of github"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = false                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  github = "https://github.com/whiteppure/"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
